package com.rajit.worldheritages.util

object Constants {

    const val DB_NAME = "WorldHeritageDB"
    const val TABLE_NAME = "HeritageTable"
    const val PAGE_SIZE = 20

    // Convert Country Abbreviation to Country Full Name
    fun convertCountryShortToFullText(abbreviation: String): String {
        return when (abbreviation) {
            "CMR" -> "Cameroon"
            "NAM" -> "Namibia"
            "ALB" -> "Albania"
            "IRL" -> "Ireland"
            "LKA" -> "Sri Lanka"
            "ROU" -> "Romania"
            "ITA" -> "Italy"
            "BOL" -> "Bolivia"
            "TGO" -> "Togo"
            "SAU" -> "Saudi Arabia"
            "BGR" -> "Bulgaria"
            "ESP" -> "Spain"
            "QAT" -> "Qatar"
            "MNG" -> "Mongolia"
            "VEN" -> "Venezuela"
            "NLD" -> "Netherlands"
            "PHL" -> "Philippines"
            "DNK" -> "Denmark"
            "KOR" -> "South Korea"
            "UKR" -> "Ukraine"
            "OMN" -> "Oman"
            "PER" -> "Peru"
            "CZE" -> "Czechia"
            "USA" -> "United States of America"
            "HND" -> "Honduras"
            "PSE" -> "State of Palestine"
            "BEN" -> "Benin"
            "CHE" -> "Switzerland"
            "SLB" -> "Solomon Islands"
            "AFG" -> "Afghanistan"
            "JOR" -> "Jordan"
            "SWE" -> "Sweden"
            "MDA" -> "Moldova"
            "ARM" -> "Armenia"
            "KGZ" -> "Kyrgyzstan"
            "UZB" -> "Uzbekistan"
            "HTI" -> "Haiti"
            "NER" -> "Niger"
            "BWA" -> "Botswana"
            "YEM" -> "Yemen"
            "PRT" -> "Portugal"
            "GIN" -> "Guinea"
            "DEU" -> "Germany"
            "MEX" -> "Mexico"
            "KHM" -> "Cambodia"
            "LSO" -> "Lesotho"
            "PAN" -> "Panama"
            "MNE" -> "Montenegro"
            "UGA" -> "Uganda"
            "PLW" -> "Palau"
            "ECU" -> "Ecuador"
            "GEO" -> "Georgia"
            "SGP" -> "Singapore"
            "NOR" -> "Norway"
            "ZWE" -> "Zimbabwe"
            "IRQ" -> "Iraq"
            "PRY" -> "Paraguay"
            "DZA" -> "Algeria"
            "SRB" -> "Serbia"
            "MRT" -> "Mauritania"
            "IRN" -> "Iran"
            "FJI" -> "Fiji"
            "ARE" -> "United Arab Emirates"
            "PNG" -> "Papua New Guinea"
            "ETH" -> "Ethiopia"
            "NPL" -> "Nepal"
            "MLT" -> "Malta"
            "AND" -> "Andorra"
            "PRK" -> "North Korea"
            "FRA" -> "France"
            "MYS" -> "Malaysia"
            "AUT" -> "Austria"
            "LCA" -> "Saint Lucia"
            "AUS" -> "Australia"
            "MLI" -> "Mali"
            "MUS" -> "Mauritius"
            "SUR" -> "Suriname"
            "MOZ" -> "Mozambique"
            "ARG" -> "Argentina"
            "SVN" -> "Slovenia"
            "GAB" -> "Gabon"
            "FIN" -> "Finland"
            "MDG" -> "Madagascar"
            "CHN" -> "China"
            "KNA" -> "Saint Kitts and Nevis"
            "VUT" -> "Vanuatu"
            "BRB" -> "Barbados"
            "LBN" -> "Lebanon"
            "PAK" -> "Pakistan"
            "TCD" -> "Chad"
            "BLZ" -> "Belize"
            "KIR" -> "Kiribati"
            "BGD" -> "Bangladesh"
            "BRA" -> "Brazil"
            "TZA" -> "Tanzania"
            "IDN" -> "Indonesia"
            "MKD" -> "North Macedonia"
            "COG" -> "Congo"
            "TUN" -> "Tunisia"
            "POL" -> "Poland"
            "LAO" -> "Laos"
            "LUX" -> "Luxembourg"
            "SLV" -> "El Salvador"
            "LVA" -> "Latvia"
            "EGY" -> "Egypt"
            "GMB" -> "Gambia"
            "MHL" -> "Marshall Islands"
            "NZL" -> "New Zealand"
            "TUR" -> "Turkey"
            "DOM" -> "Dominican Republic"
            "GHA" -> "Ghana"
            "VAT" -> "Vatican City"
            "BIH" -> "Bosnia and Herzegovina"
            "CUB" -> "Cuba"
            "IND" -> "Bharat (India)"
            "ZAF" -> "South Africa"
            "THA" -> "Thailand"
            "COD" -> "Democratic Republic of Congo"
            "LTU" -> "Lithuania"
            "KEN" -> "Kenya"
            "EST" -> "Estonia"
            "URY" -> "Uruguay"
            "SEN" -> "Senegal"
            "CYP" -> "Cyprus"
            "CAF" -> "Central African Republic"
            "TJK" -> "Tajikistan"
            "MWI" -> "Malawi"
            "LBY" -> "Libya"
            "JAM" -> "Jamaica"
            "JPN" -> "Japan"
            "KAZ" -> "Kazakhstan"
            "MAR" -> "Morocco"
            "SYR" -> "Syria"
            "BHR" -> "Bahrain"
            "DMA" -> "Dominica"
            "VNM" -> "Vietnam"
            "NIC" -> "Nicaragua"
            "BLR" -> "Belarus"
            "ZMB" -> "Zambia"
            "COL" -> "Colombia"
            "RUS" -> "Russia"
            "ISL" -> "Iceland"
            "BFA" -> "Burkina Faso"
            "CHL" -> "Chile"
            "AZE" -> "Azerbaijan"
            "ISR" -> "Israel"
            "CAN" -> "Canada"
            "SMR" -> "San Marino"
            "NGA" -> "Nigeria"
            "GBR" -> "United Kingdom"
            "GRC" -> "Greece"
            "HUN" -> "Hungary"
            "MMR" -> "Myanmar"
            "CPV" -> "Cabo Verde"
            "SVK" -> "Slovakia"
            "GTM" -> "Paraguay"
            "SDN" -> "Sudan"
            "TKM" -> "Turkmenistan"
            "CIV" -> "Côte d'Ivoire"
            "HRV" -> "Croatia"
            "BEL" -> "Belgium"
            "CRI" -> "Costa Rica"
            "SYC" -> "Seychelles"
            else -> "Unknown"
        }
    }

}